### ISSUE TITLE
`make setup` fails

### ISSUE THREAD

**Issue by smondet** [hammerlab/prohlatype#24]
Sadly, OCamlfind packages do not correspond to Opam packages:

```
 $ make setup
opam install ocamlfind ocamlbuild ppx_deriving.std nonstd sosa ocamlgraph cmdliner extlib
[ERROR] No package matches ppx_deriving.std.
```

**Comment by rleonid** [comment]
@smondet Do you want me to fix this or will you resolve this with `solvuu_build` ? I'm fine with either case; `prohlatype` is still at an early stage of development so I would use a different field in the `Makefile`, but I wonder if `solvuu_build` handles this case?

**Comment by smondet** [comment]
I'll try something with solvuu-build 👍

**Comment by rleonid** [comment]
I went with a bulky [solution](https://github.com/hammerlab/prohlatype/blob/master/Makefile#L2) for now.
