### ISSUE TITLE
Add graph merging functionality

### ISSUE THREAD

**Issue by rleonid** [hammerlab/prohlatype#43]
Merging A_gen with A_nuc would expand the range where reads could align and thereby provide more evidence.

**Comment by hammer** [comment]
@rleonid was this done with https://github.com/hammerlab/prohlatype/pull/46?

**Comment by rleonid** [comment]
Yes, the "merging" logic was finished in #47 though when I set out to work on this I also envisioned this task as including algorithms/framework to manipulate some logic for selecting what gets merged. This is the 2nd half of this issue as now completed by #60

**Comment by rleonid** [comment]
I guess, I did a bad job of laying out this task as issue #54 tracks this part. So, I'll close this issue and use #54 to track the performance of this merge.
