### ISSUE TITLE
Investigate biological K-mers

### ISSUE THREAD

**Issue by rleonid** [hammerlab/prohlatype#49]
this should improve specificity.

**Comment by hammer** [comment]
What exactly do you mean? Should we be computing statistics on the reference for frequency of kmers as we do when doing QC for variant calling?

**Comment by rleonid** [comment]
> What exactly do you mean?

The current algorithm is too general; it indexes all possible kmers not necessarily those that are biologically present. For example, if we have `A*01:` with ACGT and `A*02:` with AGGA giving us a graph where there are 1 nodes at position 0,2 and 2 nodes at position 1,3, the algorithm will add `ACGA` as a seen kmer. In practice this means that the initial indexing (based off of those kmers) will map some reads from HLA-E onto the HLA-A graph.

> Should we be computing statistics on the reference for frequency of kmers as we do when doing QC for variant calling?

I don't know. Computing the statistics isn't the hard part. But I am not familiar with how they're used in variant calling and if that is relevant.
