### ISSUE TITLE
Benchmark newly filtered UPenn data

### ISSUE THREAD

**Issue by rleonid** [hammerlab/prohlatype#70]
Will be labeled the 2016-12-21 on the progress log, even though I goofed[1] and need to re-run it.

1. Ended up mixing up the output files and only got 1/3 of the result due to A,B overwriting C (or some other combo).

**Comment by hammer** [comment]
Where can I find the progress log?

**Comment by rleonid** [comment]
It is in the project folder.

**Comment by rleonid** [comment]
This is done.
